config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "forum_threads#index"

  resources :forum_threads, only: [:show, :new, :create, :edit, :update, :destroy] do
    put :pinit, on: :member
    resources :forum_posts, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_post.rb
class ForumPost < ApplicationRecord
  belongs_to :user
  belongs_to :forum_thread, counter_cache: true

  validates :content, presence: true
end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
  extend FriendlyId

  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :forum_posts, dependent: :destroy

  validates :title, presence: true, length: {maximum: 50}
  validates :content, presence: true

  def sticky?
    sticky_order != 100
  end

  def pinit!
    self.sticky_order = 1
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :forum_threads
  has_many :forum_posts

  enum level: {member: 0, admin: 1}
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :pundit_error
  before_action :configure_permitted_parameters, if: :devise_controller?

private

  def pundit_error
    flash[:notice] = 'Tidak memiliki hak askes'
    redirect_to root_path
  end

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
    before_action :authenticate_user!, only: [:create]
    def create
    @thread = ForumThread.friendly.find(params[:forum_thread_id])
    @post = ForumPost.new(resource_params)

    @post.forum_thread = @thread
    @post.user = current_user

    if @post.save
      redirect_to forum_thread_path(@thread)
    else
      render 'forum_threads/show'
    end
  end

  private

  def resource_params
    params.require(:forum_post).permit(:content)
  end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :create]
  
  def index
    if params[:search]
      @threads = ForumThread.where('title like ?', "%#{params[:search]}%").paginate(per_page: 5, page: params[:page])
    else
      @threads = ForumThread.order(sticky_order: :asc).order(id: :desc).paginate(per_page: 5, page: params[:page])
    end
  end

  def show
    @thread = ForumThread.friendly.find(params[:id])
    @post = ForumPost.new
    @posts = @thread.forum_posts.paginate(per_page: 3, page: params[:page])
  end

  def new
    @thread = ForumThread.new
  end

  def create
    @thread = ForumThread.new(resource_params)
    @thread.user = current_user
    
    if @thread.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @thread = ForumThread.friendly.find(params[:id])
    authorize @thread
  end

  def destroy
    @thread = ForumThread.friendly.find(params[:id])
    authorize @thread

    @thread.destroy
    
    redirect_to root_path, notice: 'Thread sudah dihapus'
  end

  def update
    @thread = ForumThread.friendly.find(params[:id])
    authorize @thread
    
    if @thread.update(resource_params)
      redirect_to forum_thread_path(@thread)
    else
      render 'new'
    end
  end

  def pinit
    @thread = ForumThread.friendly.find(params[:id])
    @thread.pinit!
    authorize @thread
    
    redirect_to root_path
  end

  private

  def resource_params
    params.require(:forum_thread).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forum_threads/_form.html.erb
<% if @thread.errors.any? %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <% @thread.errors.full_messages.each do |error| %>
          <span><%= error %></span> </br>
        <% end %>
      </div>
    <% end %>
    <%= form_for @thread do |f| %>
      <div class='form-group'>  
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    
      <div class='form-group'>  
        <%= f.label :content %>
        <%= f.text_area :content, rows: 10, class: 'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.submit "Buat", class: 'btn btn-primary form-control'%>
      </div>
    <% end %>

app/views/forum_threads/edit.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= render 'form' %>
  </div>
</div>

app/views/forum_threads/index.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <% if user_signed_in? %>
      <%= link_to "Buat Diskusi", new_forum_thread_path, class: 'btn btn-primary form-control' %>
    <% end %>  

    <% @threads.each do |t| %>
      <div class='thread'>
        <h4 class='title'><%= link_to t.title.titleize, forum_thread_path(t) %> 
          
          <% if t.sticky? %>
            <span class="glyphicon glyphicon-pushpin"></span>
          <% end %>
        </h4>
        <div class='meta'>
          <p><%= I18n.l(t.created_at.to_date) %> oleh <%= t.user.name %></p> 
        </div>
  
        <div class='content'>
          <p> <%= truncate t.content, length: 200 %> </p>
        </div>

        <% if user_signed_in? %>
          <% if policy(t).pinit? %>
            <div class="action">
              <%= link_to 'Pin It',  pinit_forum_thread_path(t), class: 'btn btn-primary', method: :put %>
            </div>
          <% end %> 
        <% end %>
          
        <div class='count'>
          <p> <%= t.forum_posts_count %> obrolan </p>
        </div>
  
        <div style='clear: both;'></div>
      </div>
    <% end %>

    <%= will_paginate @threads, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/forum_threads/new.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= render 'form' %>
  </div>
</div>

app/views/forum_threads/show.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
      <div class='thread'>
        <h4 class='title'><%= @thread.title.titleize %></h4>
        <div class='meta'>
          <p><%= I18n.l(@thread.created_at.to_date) %> oleh <%= @thread.user.name %></p> 
        </div>
  
        <div class='content'>
          <p> <%= @thread.content %> </p>
        </div>

        <% if user_signed_in? %>
          <% if policy(@thread).edit? %>
            <div class="edit">
              <%= link_to 'Edit',  edit_forum_thread_path(@thread), class: 'btn btn-primary' %>
              <%= link_to 'Delete', forum_thread_path(@thread), method: :delete, data: {confirm: 'Yakin dihapus?'}, class: 'btn btn-primary' %>
            </div>
          <% end %>
        <% end %>

    <% if @thread.forum_posts.any? %>  
      <% @posts.each do |p| %>
        <div class='thread'>
          <div class='meta'>
            <p><%= I18n.l(p.created_at.to_date) %> oleh <%= p.user.name %></p> 
          </div>

          <div class='content'>
            <p> <%= p.content %> </p>
          </div>
        </div>
      <% end %>

      <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
    <% elsif user_signed_in? %>
        <p> Jadilah yang pertama berkomentar... </p>
    <% else %>
        <p> Silahkan login, untuk berkomentar... </p>
    <% end %>
    
    <% if @post.errors.any? %>
      <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <% @post.errors.full_messages.each do |error| %>
        <span><%= error %></span> </br>
        <% end %>
      </div>
    <% end %>
    <% if user_signed_in? %>
      <%= form_for [@thread, @post] do |f| %>
        <div class='form-group'>  
          <%= f.label :content %>
          <%= f.text_area :content, rows: 10, class: 'form-control' %>
        </div>
    
        <div class='form-group'>
          <%= f.submit "Buat", class: 'btn btn-primary form-control'%>
        </div>
      <% end %>
    <% end %>
    
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Forum', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%=  form_tag root_path, method: :get, class: 'navbar-form navbar-left' do %>
        <div class="form-group">
          <%= text_field_tag :search, nil, class: 'form-control' %>
        </div>
        <%= submit_tag "Cari", class: 'btn btn-default'%>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= user_signed_in? ? current_user.name : 'Hallo guest' %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Daftar', new_user_registration_path %></li>
              <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
      <div class='container'>
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        <% end %> 
        
        <%= yield %>
      </div>
  </body>
</html>